language: node_js
node_js:
- 11.6.0

cache: yarn 

install:
 - yarn install

script: 
 - make build-mkdocs
#   - yarn test 
#   - yarn run build

deploy:
   provider: pages 
   skip-cleanup: true 
   github-token: $GITHUB_TOKEN
   local_dir: "./site"
   keep_history: true
   on:
    branch: master 
  

# before_install:
# install: 
# before_script:
# script:
# after_sucess:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy: