script: 
 - make build-mkdocs

deploy:
   provider: pages 
   skip-cleanup: true 
   github-token: $GITHUB_TOKEN
   local_dir: "./site"
   keep_history: false
   on:
    branch: master 
  
#######
# before_install:
# install: 
# before_script:
# script:
# after_sucess:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy: