# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

site_name: mY Docs
site_description: Testing Github pages

repo_name: ysfkel/my-github-pages
repo_url: https://github.com/ysfkel/my-github-pages

# Configuration
markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: black
  favicon: img/favicon.ico
nav:
  - Testing: test.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ysfkel/my-github-pages
